### ISSUE TITLE
requirements.txt missing

### ISSUE THREAD

**Issue by tumregels** [PacktPublishing/In-Memory-Analytics-with-Apache-Arrow-#1]
Congratulations on the book! 
Great work!

Would have been great to have `requirements.txt` in each python folder.

**Comment by nithikpackt** [comment]
@tumregels, Thank you for feedback. Also, regarding the requirement.txt file, there is a workaround you could try to automatically generate requirement.txt for python files in a directory:

# install
`pip3 install pipreqs`

# Run in current directory
`python3 -m  pipreqs.pipreqs .`

Hope this helps.
